# Generated by Django 4.2.3 on 2023-07-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_moderator_profile_student_remove_studentprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to='profile_pictures/'),
        ),
    ]
