# Generated by Django 4.2.4 on 2023-08-10 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingPracticeSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('transcript', models.TextField(default='')),
                ('is_successful', models.BooleanField(default=False)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.speakingpractice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'practice')},
            },
        ),
        migrations.CreateModel(
            name='TranslationPracticeSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('is_successful', models.BooleanField(default=False)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.translationpractice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'practice')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='translationpracticesolved',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='translationpracticesolved',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='translationpracticesolved',
            name='user',
        ),
        migrations.RenameField(
            model_name='speakingpracticeevaluation',
            old_name='is_done',
            new_name='is_completed',
        ),
        migrations.DeleteModel(
            name='SpeakingPracticeSolved',
        ),
        migrations.DeleteModel(
            name='TranslationPracticeSolved',
        ),
    ]
