# Generated by Django 4.2.3 on 2023-07-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='flag',
            field=models.ImageField(default='default_flag_pic.jpg ', upload_to='flag_pictures/'),
        ),
    ]
