# Generated by Django 4.2.3 on 2023-07-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_is_active_speakingpractice_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationpractice',
            name='choice_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='translationpractice',
            name='choice_2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='translationpractice',
            name='choice_3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='translationpractice',
            name='answer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='translationpractice',
            name='question',
            field=models.CharField(default='', max_length=255),
        ),
    ]
