# Generated by Django 4.2.3 on 2023-07-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_translationpractice_choice_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationpractice',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='translationpractice',
            name='choice_1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='translationpractice',
            name='choice_2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='translationpractice',
            name='choice_3',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='translationpractice',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='translationpractice',
            name='title',
            field=models.TextField(),
        ),
    ]
