# Generated by Django 4.2.3 on 2023-07-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationpractice',
            name='difficulty',
            field=models.SmallIntegerField(choices=[(1, 'Easy'), (2, 'Intermediate'), (3, 'Hard')], default=0),
        ),
    ]
