# Generated by Django 4.2.3 on 2023-07-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_speakingpracticesolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
