# Generated by Django 4.2.3 on 2023-07-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakingpractice',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='translationpractice',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
