# Generated by Django 4.2.3 on 2023-07-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_audiorecord_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiorecord',
            name='audio_file',
            field=models.FileField(upload_to=''),
        ),
    ]
