# Generated by Django 4.2.3 on 2023-07-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_audiorecord_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language_code',
            field=models.CharField(default='en-US'),
        ),
    ]
