# Generated by Django 4.2.3 on 2023-07-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language_code',
            field=models.CharField(),
        ),
    ]
