# Generated by Django 4.2.3 on 2023-07-31 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0017_alter_course_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingpracticesolved',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='audiorecord',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.speakingpractice'),
        ),
        migrations.AlterField(
            model_name='audiorecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
