# Generated by Django 4.2.3 on 2023-07-31 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_speakingpracticesolved_point_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiorecord',
            old_name='user',
            new_name='owner',
        ),
        migrations.CreateModel(
            name='SpeakingPracticeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('audio_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.audiorecord')),
            ],
        ),
    ]
