# Generated by Django 4.2.3 on 2023-07-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_rename_user_audiorecord_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingpracticesolved',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
