# Generated by Django 4.2.4 on 2023-08-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_speakingpracticesolved_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingpracticesolved',
            name='transcript',
            field=models.TextField(default=''),
        ),
    ]
